apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - image: grafana/grafana-enterprise:12.3-ubuntu
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: nvcl-db
              mountPath: /nvcl-db
          securityContext:
            runAsUser: {{ values.nfs.security.userId }}
            runAsGroup: {{ values.nfs.security.groupId }}
      restartPolicy: Always
      volumes:
        - name: grafana-config
          nfs:
            server: {{ values.nfs.vols.grafanaConfig.server }}
            path: {{ values.nfs.vols.grafanaConfig.path }}
        - name: grafana-data
          nfs:
            server: {{ values.nfs.vols.grafanaData.server }}
            path: {{ values.nfs.vols.grafanaData.path }}
        - name: nvcl-db
          nfs:
            server: {{ values.nfs.vols.nvclDb.server }}
            path: {{ values.nfs.vols.nvclDb.path }}

