apiVersion: v2
name: nvcl-report-app
description: A Helm chart for NVCL Reporting application
type: application
version: 0.1.0        # Chart version
appVersion: "1.0"     # NVCL Reporting Application version
